### ISSUE TITLE
Add a usage example explaining nnbench to the new comers

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#17]
NOTE: this ticket is a subtask of [Complete documentation task](https://github.com/aai-institute/MLOps-Engineering/issues/38).
We need a simple and illustrative explanation of the product purpose and usage for the people visiting the product repository for the first time.
We will achieve this by adding a usage example (code snippets / notebook / equivalent) to the product documentation. 
This example should focus on illustrating the nnbench mechanism, but at the same time, it should be embedded in a real ML use case.
Ideally this usage example should enhance its adoption to a user's code/user's ML case (after required adjustments of a user's code).   

Merged here https://github.com/aai-institute/nnbench/pull/25

**Comment by Maciej818** [comment]
@maxmynter 
1. Could you please link [PR](https://github.com/aai-institute/nnbench/pull/25) - I think I am not technically able to do this myself.
2. As I've already mentioned: I love the example as it clearly conveys how to simply apply the library in your project. 
3. As now we have everything in one file "In the following simple example, we put the training and benchmarking logic in the same file.", do we still need this: `from training import model, X_test, y_test ` ?
4. On a separate note: maybe worth mentioning in README: For usage example see quickstart.md.

**Comment by maxmynter** [comment]
The issue [PR](https://github.com/aai-institute/nnbench/pull/25)
