### ISSUE TITLE
Add user guides on various topics to documentation

### ISSUE THREAD

**Issue by nicholasjng** [aai-institute/nnbench#27]
With the quickstart (introductory example based on scikit-learn) merged (see #25), we can follow it up with more thorough guides on different important cornerstones of the package.

- [ ] #34
- [ ] #32
- [ ] #35
- [ ] #37
- [ ] #38

**Comment by Maciej818** [comment]
Closing this ticket as the scope was already addressed by separate tickets and will be tracked there.
