### ISSUE TITLE
Defining and parametrizing benchmarks by applying decorators (`@benchmark,@parametrize,@product)` - motivation, behavior, and one usage example for each.

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#33]

**Comment by msavinash** [comment]
I don't understand how parametrize is supposed to work. From my understanding its something like this:
```
parametrize_parameters = [
    {"y_test": [1, 2, 3], "y_pred": [4, 5, 6]},
    {"y_test": [1, 2, 3], "y_pred": [1, 2, 3]},
]

@nnbench.parametrize(parameters=parametrize_parameters)
def accuracy(model: base.BaseEstimator, y_test: np.ndarray, y_pred: np.ndarray) -> float:
    accuracy = metrics.accuracy_score(y_test, y_pred)
    return accuracy

```
Is this accurate?

**Comment by nicholasjng** [comment]
> Is this accurate?

Yes. 

(The arguments in the decorator dictionaries should match the parametrized benchmark function's typing, so the arguments should be `np.array([1, 2, 3]),  np.array([4, 5, 6]), ...`, but you got it right conceptually.)

**Comment by Maciej818** [comment]
This issue duplicates #34 - I close it. Relevant comments (above) were copy-pasted to #34 .
