### ISSUE TITLE
Re-evaluate `Benchmarkable` vs. `Benchmark` split for polymorphism

### ISSUE THREAD

**Issue by nicholasjng** [aai-institute/nnbench#4]
For the time being, we can roll just fine with `Benchmark` being the only admissible benchmark type.

However, if users want to roll their own runners, they might also want to run their own benchmarks. In that case, all of the decorator facilities in `nnbench.core` will not do the correct thing anymore, since they unconditionally yield `Benchmark`s, which would not be collected with the base `BenchmarkRunner.collect()` method.

A solution is to define a base `Benchmarkable` class (name TBD, could also be `BenchmarkBase` or similar), and create conversions to the respective benchmark type by a builder pattern / Python classmethod.

Case in point:

```python
from nnbench import AbstractBenchmarkRunner, Benchmark

class MyBenchmark(Benchmark):
    @classmethod
    def create(b: Benchmarkable):
        ...

class MyBenchmarkRunner(AbstractBenchmarkRunner):
    benchmark_type = MyBenchmark

```

And then have `nnbench.benchmark` and `nnbench.parametrize` decorators yield `Benchmarkable`s, respectively.

**Comment by Maciej818** [comment]
Not requested/not necessary for now (can be reopened if required in the future).
