### ISSUE TITLE
Add example: Streaming results to a database

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#66]
Add example or tutorial to the documentation on streaming results to a database with a custom data sink.
Please note: https://duckdb.org/2023/03/03/json.html for getting started with DuckDB.

- [x] Prepare BQ example
- [ ] Check/verify SQL model
- [ ] Decide on what API we go forward with

**Comment by nicholasjng** [comment]
DuckDB is done, BQ is next:

- Schema: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
- Table creation: https://cloud.google.com/bigquery/docs/tables#python

**Comment by Maciej818** [comment]
@nicholasjng I assume that the PR [#85](https://github.com/aai-institute/nnbench/pull/85) addresses the first task in this ticket ("Prepare BQ example") and the two following are still to be done (" Check/verify SQL model" and "Decide on what API we go forward with") - I created a separate ticket for them https://github.com/aai-institute/nnbench/issues/86.
Please shout if my assumption is wrong.
